const productos = [
    {id: 1,    
    nombre: "Correa extensible",      
    precio : 1300,     
    unidad: 0,     
    imagen: "assets/ImgProductos/correa-extensible.webp"},
    
    {id: 2,    
    nombre: "Hueso de goma",          
    precio : 900,      
    unidad: 0,     
    imagen: "assets/ImgProductos/huesodegoma.webp"},

    {id: 3,    
    nombre: "Comedero",               
    precio : 1150,     
    unidad: 0,     
    imagen: "assets/ImgProductos/comedero.webp"},
    
    {id: 4,    
    nombre: "Collar",                 
    precio : 600,      
    unidad: 0,     
    imagen: "assets/ImgProductos/collar.webp"},
    
    {id: 5,    
    nombre: "Piedras sanitarias",     
    precio : 450,      
    unidad: 0,     
    imagen: "assets/ImgProductos/piedritas.webp"},

    {id: 6,    
    nombre: "Alimento balanceado",      
    precio : 8850,     
    unidad: 0,     
    imagen: "assets/ImgProductos/balanceado.webp"},
        
    {id: 7,    
    nombre: "Pipeta",          
    precio : 2810,      
    unidad: 0,     
    imagen: "assets/ImgProductos/pipeta.webp"},
    
    {id: 8,    
    nombre: "Bolso transportador",               
    precio : 11570,     
    unidad: 0,     
    imagen: "assets/ImgProductos/bolsotransportador.webp"},
        
    {id: 9,    
    nombre: "Cucha",                 
    precio : 6740,      
    unidad: 0,     
    imagen: "assets/ImgProductos/cucha.webp"},
        
    {id: 10,    
    nombre: "Rodillo adhesivo",     
    precio : 1890,      
    unidad: 0,     
    imagen: "assets/ImgProductos/rodillo.webp"},

    {id: 11,    
    nombre: "Cepillo",                 
    precio : 2300,      
    unidad: 0,     
    imagen: "assets/ImgProductos/cepillo.webp"},
            
    {id: 12,    
    nombre: "Soga",     
    precio : 1500,      
    unidad: 0,     
    imagen: "assets/ImgProductos/soga.webp"},
]